### ISSUE TITLE
Errors in run.sh

### ISSUE THREAD

**Issue by sebnash** [grahamgilbert/docker-puppetserver#1]
When running a container from this image, the logs show:

```
/run.sh: line 27: null: command not found
/run.sh: line 28: [: null: integer expression expected
```

**Comment by grahamgilbert** [comment]
Ah, I left this in when testing something and didn't notice as I'm using [grahamgilbert/docker-sal-puppetserver](https://github.com/grahamgilbert/docker-sal-puppetserver) which overrides `run.sh` with it's own.
